export const PermissionConstants = {
    // AUTH SERVICE
    AuthService: {
        // CRUD USER
        CreateUser: 'AUTH_SERVICE_CREATE_USER',
        ReadUser: 'AUTH_SERVICE_READ_USER',
        UpdateUser: 'AUTH_SERVICE_UPDATE_USER',
        DeleteUser: 'AUTH_SERVICE_DELETE_USER',

        // CRUD ROLE
        CreateRole: 'AUTH_SERVICE_CREATE_ROLE',
        ReadRole: 'AUTH_SERVICE_READ_ROLE',
        UpdateRole: 'AUTH_SERVICE_UPDATE_ROLE',
        DeleteRole: 'AUTH_SERVICE_DELETE_ROLE',

        // CRUD PERMISSION
        CreatePermission: 'AUTH_SERVICE_CREATE_PERMISSION',
        ReadPermission: 'AUTH_SERVICE_READ_PERMISSION',
        UpdatePermission: 'AUTH_SERVICE_UPDATE_PERMISSION',
        DeletePermission: 'AUTH_SERVICE_DELETE_PERMISSION',

        // CRUD ROLE PERMISSION
        CreateRolePermission: 'AUTH_SERVICE_CREATE_ROLE_PERMISSION',
        ReadRolePermission: 'AUTH_SERVICE_READ_ROLE_PERMISSION',
        UpdateRolePermission: 'AUTH_SERVICE_UPDATE_ROLE_PERMISSION',
        DeleteRolePermission: 'AUTH_SERVICE_DELETE_ROLE_PERMISSION',

        // CRUD USER ROLE
        CreateUserRole: 'AUTH_SERVICE_CREATE_USER_ROLE',
        ReadUserRole: 'AUTH_SERVICE_READ_USER_ROLE',
        UpdateUserRole: 'AUTH_SERVICE_UPDATE_USER_ROLE',
    },

    // MASTER DATA SERVICE
    MasterDataService: {
        // CRUD STUDENTS
        CreateStudents: 'MASTER_DATA_SERVICE_CREATE_STUDENTS',
        ReadStudents: 'MASTER_DATA_SERVICE_READ_STUDENTS',
        UpdateStudents: 'MASTER_DATA_SERVICE_UPDATE_STUDENTS',
        DeleteStudents: 'MASTER_DATA_SERVICE_DELETE_STUDENTS',

        // CRUD TEACHERS
        CreateTeachers: 'MASTER_DATA_SERVICE_CREATE_TEACHERS',
        ReadTeachers: 'MASTER_DATA_SERVICE_READ_TEACHERS',
        UpdateTeachers: 'MASTER_DATA_SERVICE_UPDATE_TEACHERS',
        DeleteTeachers: 'MASTER_DATA_SERVICE_DELETE_TEACHERS',

        // CRUD PARENTS
        CreateParents: 'MASTER_DATA_SERVICE_CREATE_PARENTS',
        ReadParents: 'MASTER_DATA_SERVICE_READ_PARENTS',
        UpdateParents: 'MASTER_DATA_SERVICE_UPDATE_PARENTS',
        DeleteParents: 'MASTER_DATA_SERVICE_DELETE_PARENTS',

        // CRUD STAFFS
        CreateStaffs: 'MASTER_DATA_SERVICE_CREATE_STAFFS',
        ReadStaffs: 'MASTER_DATA_SERVICE_READ_STAFFS',
        UpdateStaffs: 'MASTER_DATA_SERVICE_UPDATE_STAFFS',
        DeleteStaffs: 'MASTER_DATA_SERVICE_DELETE_STAFFS',

        // CRUD ACADEMIC YEARS
        CreateAcademicYears: 'MASTER_DATA_SERVICE_CREATE_ACADEMIC_YEARS',
        ReadAcademicYears: 'MASTER_DATA_SERVICE_READ_ACADEMIC_YEARS',
        UpdateAcademicYears: 'MASTER_DATA_SERVICE_UPDATE_ACADEMIC_YEARS',
        DeleteAcademicYears: 'MASTER_DATA_SERVICE_DELETE_ACADEMIC_YEARS',

        // CRUD SEMESTERS
        CreateSemesters: 'MASTER_DATA_SERVICE_CREATE_SEMESTERS',
        ReadSemesters: 'MASTER_DATA_SERVICE_READ_SEMESTERS',
        UpdateSemesters: 'MASTER_DATA_SERVICE_UPDATE_SEMESTERS',
        DeleteSemesters: 'MASTER_DATA_SERVICE_DELETE_SEMESTERS',

        // CRUD GRADES
        CreateGrades: 'MASTER_DATA_SERVICE_CREATE_GRADES',
        ReadGrades: 'MASTER_DATA_SERVICE_READ_GRADES',
        UpdateGrades: 'MASTER_DATA_SERVICE_UPDATE_GRADES',
        DeleteGrades: 'MASTER_DATA_SERVICE_DELETE_GRADES',

        // CRUD MAJORS
        CreateMajors: 'MASTER_DATA_SERVICE_CREATE_MAJORS',
        ReadMajors: 'MASTER_DATA_SERVICE_READ_MAJORS',
        UpdateMajors: 'MASTER_DATA_SERVICE_UPDATE_MAJORS',
        DeleteMajors: 'MASTER_DATA_SERVICE_DELETE_MAJORS',

        // CRUD CLASSES
        CreateClasses: 'MASTER_DATA_SERVICE_CREATE_CLASSES',
        ReadClasses: 'MASTER_DATA_SERVICE_READ_CLASSES',
        UpdateClasses: 'MASTER_DATA_SERVICE_UPDATE_CLASSES',
        DeleteClasses: 'MASTER_DATA_SERVICE_DELETE_CLASSES',

        // CRUD STUDENT CLASSES
        CreateStudentClasses: 'MASTER_DATA_SERVICE_CREATE_STUDENT_CLASSES',
        ReadStudentClasses: 'MASTER_DATA_SERVICE_READ_STUDENT_CLASSES',
        UpdateStudentClasses: 'MASTER_DATA_SERVICE_UPDATE_STUDENT_CLASSES',
        DeleteStudentClasses: 'MASTER_DATA_SERVICE_DELETE_STUDENT_CLASSES',

        // CRUD SUBJECTS
        CreateSubjects: 'MASTER_DATA_SERVICE_CREATE_SUBJECTS',
        ReadSubjects: 'MASTER_DATA_SERVICE_READ_SUBJECTS',
        UpdateSubjects: 'MASTER_DATA_SERVICE_UPDATE_SUBJECTS',
        DeleteSubjects: 'MASTER_DATA_SERVICE_DELETE_SUBJECTS',

        // CRUD CLASS SUBJECTS
        CreateClassSubjects: 'MASTER_DATA_SERVICE_CREATE_CLASS_SUBJECTS',
        ReadClassSubjects: 'MASTER_DATA_SERVICE_READ_CLASS_SUBJECTS',
        UpdateClassSubjects: 'MASTER_DATA_SERVICE_UPDATE_CLASS_SUBJECTS',
        DeleteClassSubjects: 'MASTER_DATA_SERVICE_DELETE_CLASS_SUBJECTS',

        // CRUD CLASS SUBJECT TEACHERS
        CreateClassSubjectTeachers:
            'MASTER_DATA_SERVICE_CREATE_CLASS_SUBJECT_TEACHERS',
        ReadClassSubjectTeachers:
            'MASTER_DATA_SERVICE_READ_CLASS_SUBJECT_TEACHERS',
        UpdateClassSubjectTeachers:
            'MASTER_DATA_SERVICE_UPDATE_CLASS_SUBJECT_TEACHERS',
        DeleteClassSubjectTeachers:
            'MASTER_DATA_SERVICE_DELETE_CLASS_SUBJECT_TEACHERS',
    },
};
