export const PERMISSION = {
    // AUTH SERVICE
    AUTH_SERVICE: {
        // CRUD USER
        CREATE_USER: 'AUTH_SERVICE_CREATE_USER',
        READ_USER: 'AUTH_SERVICE_READ_USER',
        UPDATE_USER: 'AUTH_SERVICE_UPDATE_USER',
        DELETE_USER: 'AUTH_SERVICE_DELETE_USER',

        // CRUD ROLE
        CREATE_ROLE: 'AUTH_SERVICE_CREATE_ROLE',
        READ_ROLE: 'AUTH_SERVICE_READ_ROLE',
        UPDATE_ROLE: 'AUTH_SERVICE_UPDATE_ROLE',
        DELETE_ROLE: 'AUTH_SERVICE_DELETE_ROLE',

        // CRUD PERMISSION
        CREATE_PERMISSION: 'AUTH_SERVICE_CREATE_PERMISSION',
        READ_PERMISSION: 'AUTH_SERVICE_READ_PERMISSION',
        UPDATE_PERMISSION: 'AUTH_SERVICE_UPDATE_PERMISSION',
        DELETE_PERMISSION: 'AUTH_SERVICE_DELETE_PERMISSION',

        // CRUD ROLE PERMISSION
        CREATE_ROLE_PERMISSION: 'AUTH_SERVICE_CREATE_ROLE_PERMISSION',
        READ_ROLE_PERMISSION: 'AUTH_SERVICE_READ_ROLE_PERMISSION',
        UPDATE_ROLE_PERMISSION: 'AUTH_SERVICE_UPDATE_ROLE_PERMISSION',
        DELETE_ROLE_PERMISSION: 'AUTH_SERVICE_DELETE_ROLE_PERMISSION',

        // CRUD USER ROLE
        CREATE_USER_ROLE: 'AUTH_SERVICE_CREATE_USER_ROLE',
        READ_USER_ROLE: 'AUTH_SERVICE_READ_USER_ROLE',
        UPDATE_USER_ROLE: 'AUTH_SERVICE_UPDATE_USER_ROLE',
    },

    // MASTER DATA SERVICE
    MASTER_DATA_SERVICE: {
        // CRUD STUDENTS
        CREATE_STUDENTS: 'MASTER_DATA_SERVICE_CREATE_STUDENTS',
        READ_STUDENTS: 'MASTER_DATA_SERVICE_READ_STUDENTS',
        UPDATE_STUDENTS: 'MASTER_DATA_SERVICE_UPDATE_STUDENTS',
        DELETE_STUDENTS: 'MASTER_DATA_SERVICE_DELETE_STUDENTS',

        // CRUD TEACHERS
        CREATE_TEACHERS: 'MASTER_DATA_SERVICE_CREATE_TEACHERS',
        READ_TEACHERS: 'MASTER_DATA_SERVICE_READ_TEACHERS',
        UPDATE_TEACHERS: 'MASTER_DATA_SERVICE_UPDATE_TEACHERS',
        DELETE_TEACHERS: 'MASTER_DATA_SERVICE_DELETE_TEACHERS',

        // CRUD PARENTS
        CREATE_PARENTS: 'MASTER_DATA_SERVICE_CREATE_PARENTS',
        READ_PARENTS: 'MASTER_DATA_SERVICE_READ_PARENTS',
        UPDATE_PARENTS: 'MASTER_DATA_SERVICE_UPDATE_PARENTS',
        DELETE_PARENTS: 'MASTER_DATA_SERVICE_DELETE_PARENTS',

        // CRUD STAFFS
        CREATE_STAFFS: 'MASTER_DATA_SERVICE_CREATE_STAFFS',
        READ_STAFFS: 'MASTER_DATA_SERVICE_READ_STAFFS',
        UPDATE_STAFFS: 'MASTER_DATA_SERVICE_UPDATE_STAFFS',
        DELETE_STAFFS: 'MASTER_DATA_SERVICE_DELETE_STAFFS',

        // CRUD ACADEMIC YEARS
        CREATE_ACADEMIC_YEARS: 'MASTER_DATA_SERVICE_CREATE_ACADEMIC_YEARS',
        READ_ACADEMIC_YEARS: 'MASTER_DATA_SERVICE_READ_ACADEMIC_YEARS',
        UPDATE_ACADEMIC_YEARS: 'MASTER_DATA_SERVICE_UPDATE_ACADEMIC_YEARS',
        DELETE_ACADEMIC_YEARS: 'MASTER_DATA_SERVICE_DELETE_ACADEMIC_YEARS',

        // CRUD SEMESTERS
        CREATE_SEMESTERS: 'MASTER_DATA_SERVICE_CREATE_SEMESTERS',
        READ_SEMESTERS: 'MASTER_DATA_SERVICE_READ_SEMESTERS',
        UPDATE_SEMESTERS: 'MASTER_DATA_SERVICE_UPDATE_SEMESTERS',
        DELETE_SEMESTERS: 'MASTER_DATA_SERVICE_DELETE_SEMESTERS',

        // CRUD GRADES
        CREATE_GRADES: 'MASTER_DATA_SERVICE_CREATE_GRADES',
        READ_GRADES: 'MASTER_DATA_SERVICE_READ_GRADES',
        UPDATE_GRADES: 'MASTER_DATA_SERVICE_UPDATE_GRADES',
        DELETE_GRADES: 'MASTER_DATA_SERVICE_DELETE_GRADES',

        // CRUD MAJORS
        CREATE_MAJORS: 'MASTER_DATA_SERVICE_CREATE_MAJORS',
        READ_MAJORS: 'MASTER_DATA_SERVICE_READ_MAJORS',
        UPDATE_MAJORS: 'MASTER_DATA_SERVICE_UPDATE_MAJORS',
        DELETE_MAJORS: 'MASTER_DATA_SERVICE_DELETE_MAJORS',

        // CRUD CLASSES
        CREATE_CLASSES: 'MASTER_DATA_SERVICE_CREATE_CLASSES',
        READ_CLASSES: 'MASTER_DATA_SERVICE_READ_CLASSES',
        UPDATE_CLASSES: 'MASTER_DATA_SERVICE_UPDATE_CLASSES',
        DELETE_CLASSES: 'MASTER_DATA_SERVICE_DELETE_CLASSES',

        // CRUD STUDENT CLASSES
        CREATE_STUDENT_CLASSES: 'MASTER_DATA_SERVICE_CREATE_STUDENT_CLASSES',
        READ_STUDENT_CLASSES: 'MASTER_DATA_SERVICE_READ_STUDENT_CLASSES',
        UPDATE_STUDENT_CLASSES: 'MASTER_DATA_SERVICE_UPDATE_STUDENT_CLASSES',
        DELETE_STUDENT_CLASSES: 'MASTER_DATA_SERVICE_DELETE_STUDENT_CLASSES',

        // CRUD SUBJECTS
        CREATE_SUBJECTS: 'MASTER_DATA_SERVICE_CREATE_SUBJECTS',
        READ_SUBJECTS: 'MASTER_DATA_SERVICE_READ_SUBJECTS',
        UPDATE_SUBJECTS: 'MASTER_DATA_SERVICE_UPDATE_SUBJECTS',
        DELETE_SUBJECTS: 'MASTER_DATA_SERVICE_DELETE_SUBJECTS',

        // CRUD CLASS SUBJECTS
        CREATE_CLASS_SUBJECTS: 'MASTER_DATA_SERVICE_CREATE_CLASS_SUBJECTS',
        READ_CLASS_SUBJECTS: 'MASTER_DATA_SERVICE_READ_CLASS_SUBJECTS',
        UPDATE_CLASS_SUBJECTS: 'MASTER_DATA_SERVICE_UPDATE_CLASS_SUBJECTS',
        DELETE_CLASS_SUBJECTS: 'MASTER_DATA_SERVICE_DELETE_CLASS_SUBJECTS',

        // CRUD CLASS SUBJECT TEACHERS
        CREATE_CLASS_SUBJECT_TEACHERS: 'MASTER_DATA_SERVICE_CREATE_CLASS_SUBJECT_TEACHERS',
        READ_CLASS_SUBJECT_TEACHERS: 'MASTER_DATA_SERVICE_READ_CLASS_SUBJECT_TEACHERS',
        UPDATE_CLASS_SUBJECT_TEACHERS: 'MASTER_DATA_SERVICE_UPDATE_CLASS_SUBJECT_TEACHERS',
        DELETE_CLASS_SUBJECT_TEACHERS: 'MASTER_DATA_SERVICE_DELETE_CLASS_SUBJECT_TEACHERS',
    },
};
